language: node_js
node_js:
  - 8
before_script:
  - cp ./.env.template ./.env
  - npm install
  - npm run build:dev
  - npm start >> /dev/null &
  - sleep 5
script:
  - npm test
after_success:
  - npm run coverage
